name: build

on:
  schedule:
    - cron: "42 6 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      tag: ${{ steps.remote-tag.outputs.value }}
      publish: ${{ steps.publish.outputs.value }}

    steps:
      - name: Get remote tag
        id: remote-tag
        run: |
          tag=$(gh release list --repo vim/vim-win32-installer --limit 1 --exclude-drafts --json tagName --jq '.[] |.tagName')

          if [ $? -ne 0 ]
          then
            exit $?
          fi

          echo "value=$tag" |tee -a "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get local tag
        id: local-tag
        run: |
          tag=$(gh release list --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} --limit 1 --exclude-drafts --json tagName --jq '.[] |.tagName')

          if [ $? -ne 0 ]
          then
            exit $?
          fi

          echo "value=$tag" |tee -a "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set publish condition
        id: publish
        shell: pwsh
        run: |
          $remoteVersion = [Version]::new('${{ steps.remote-tag.outputs.value }}'.TrimStart('v'))

          if ('${{ steps.local-tag.outputs.value }}')
          {
            $localVersion = [Version]::new('${{ steps.local-tag.outputs.value }}'.TrimStart('v'))
          }
          else
          {
            $localVersion = [Version]::new()
          }

          $required = $remoteVersion -gt $localVersion
          'value={0}' -f $required |Tee-Object -FilePath $env:GITHUB_OUTPUT -Append

  build:
    runs-on: windows-latest
    permissions:
      contents: write
    timeout-minutes: 5
    needs: check

    steps:
      - uses: actions/checkout@v6

      - name: Set version
        id: version
        run: |
          $tag = '${{ needs.check.outputs.tag }}'.TrimStart('v')
          $version = [version]::new($tag)
          'version={0}' -f $version |Tee-Object -FilePath $env:GITHUB_OUTPUT -Append
          'major={0}' -f $version.Major |Tee-Object -FilePath $env:GITHUB_OUTPUT -Append
          'minor={0}' -f $version.Minor |Tee-Object -FilePath $env:GITHUB_OUTPUT -Append
          'build={0}' -f $version.Build |Tee-Object -FilePath $env:GITHUB_OUTPUT -Append

      - name: Setup wix
        run: |
          dotnet.exe tool install --global wix --version 6.0.2 --verbosity diag

          wix.exe extension add WixToolset.UI.wixext/6.0.2 --global
          wix.exe extension add WixToolset.Util.wixext/6.0.2 --global
          wix.exe extension list --global

      - name: Download vim
        run: gh.exe release download ${{ needs.check.outputs.tag }} --pattern '*_x64.zip' --repo vim/vim-win32-installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract vim
        run: Expand-Archive -Path '*_x64.zip' -DestinationPath build -ErrorAction Stop

      - name: Prepare vim
        run: |
          Remove-Item ./build/vim/vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}/GvimExt32/GvimExt.reg -Force -ErrorAction Stop
          Remove-Item ./build/vim/vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}/GvimExt32/README.txt -Force -ErrorAction Stop
          Remove-Item ./build/vim/vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}/GvimExt64/GvimExt.reg -Force -ErrorAction Stop
          Remove-Item ./build/vim/vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}/GvimExt64/README.txt -Force -ErrorAction Stop
          Remove-Item ./build/vim/vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}/install.exe -Force -ErrorAction Stop
          Remove-Item ./build/vim/vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}/uninstall.exe -Force -ErrorAction Stop
          Remove-Item ./build/vim/vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}/uninstall.txt -Force -ErrorAction Stop

      - name: Build msi
        run: |
          wix.exe `
            build `
            -arch x64 `
            -src src\Product.wxs `
            -d ProductSource="$(Resolve-Path 'build\vim\vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}')" `
            -d SrcDirectory="$(Resolve-Path 'src')" `
            -d ProductTag="${{ needs.check.outputs.tag }}" `
            -d ProductVersion="${{ steps.version.outputs.version }}" `
            -d ProductVersionMajor="${{ steps.version.outputs.major }}" `
            -d ProductVersionMinor="${{ steps.version.outputs.minor }}" `
            -ext WixToolset.UI.wixext `
            -ext WixToolset.Util.wixext `
            -out vim.msi

      - name: Validate msi
        run: wix.exe msi validate vim.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./vim.msi
          if-no-files-found: error

      - name: Test installer
        run: |
          $process = Start-Process msiexec.exe -ArgumentList '/i','vim.msi','/qn' -Wait -NoNewWindow -PassThru -ErrorAction Stop
          if ($process.ExitCode -ne 0)
          {
              throw 'Non zero exit code: "{0}".' -f $process.ExitCode
          }

          $path = Join-Path $env:ProgramFiles 'vim\vim${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}\vim.exe' -Resolve -ErrorAction Stop
          & $path --version

      - name: Publish release
        if: needs.check.outputs.publish == 'True'
        run: gh.exe release create ${{ needs.check.outputs.tag }} --title ${{ needs.check.outputs.tag }} --notes 'Vim Windows x64 build packaged as an msi.' vim.msi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
